---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
  namespace: default
  labels:
    app: hashgenerator
spec:
  selector:
    matchLabels:
      app: hashgenerator
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      containers:
        - name: hashgenerator
          image: jakousa/dwk-app1:b7fc18de2376da80ff0cfc72cf581a9f94d10e64
          imagePullPolicy: IfNotPresent
